import turtle 

wn = turtle.Screen() 
player = turtle.Turtle() 
player.shape("turtle") 
player.goto(0,0) 
player.left(180) 
player.forward(80) 
player.left(90) 
player.forward(160) 
player.left(90) 
player.forward(80) 
player.left(90) 
player.forward(80) 
player.left(90) 
player.forward(80) 
turtle.mainloop()